version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build and install BuildX
          command: |
            docker build --platform=local -o . git://github.com/docker/buildx && \
            mkdir -p ~/.docker/cli-plugins && \
            mv buildx ~/.docker/cli-plugins/docker-buildx

      - run:
          name: Login to Docker Hub
          command: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_ACCESS_TOKEN}"

      - run:
          name: Build Docker image
          command: |
            docker buildx build \
              --platform ${BUILDX_PLATFORM} \
              --tag oogali/rtpproxy .

      - run:
          name: Tag Docker image
          command: |
            docker tag ...

      - run:
          name: Push to Docker Hub
          command: |
            docker push oogali/rtpproxy:...
